#ifndef TERRAINS_H
#define TERRAINS_H

enum Terrain {
    TERRAIN_GRASS,
    TERRAIN_LAND,
    TERRAIN_SAND,
    TERRAIN_STONE,
    TERRAIN_WALL,
    TERRAIN_WATER,
    TERRAIN_OUT_OF_BOUNDARIES
};

#endif // TERRAINS_H
